
JOINT_MAX_ANGLE = []
JOINT_MIN_ANGLE = []

JOINT_MAX_ANGLE[0] = 270
JOINT_MAX_ANGLE[1] = 270
JOINT_MAX_ANGLE[2] = 270
JOINT_MAX_ANGLE[3] = 270
JOINT_MAX_ANGLE[4] = 270
JOINT_MAX_ANGLE[5] = 270

JOINT_MIN_ANGLE[0] = 0
JOINT_MIN_ANGLE[1] = 0
JOINT_MIN_ANGLE[2] = 0
JOINT_MIN_ANGLE[3] = 0
JOINT_MIN_ANGLE[4] = 0
JOINT_MIN_ANGLE[5] = 0

JOINT_PWM_CHANNELS = []

JOINT_PWM_CHANNELS[0] = 0
JOINT_PWM_CHANNELS[1] = 1
JOINT_PWM_CHANNELS[2] = 2
JOINT_PWM_CHANNELS[3] = 3
JOINT_PWM_CHANNELS[4] = 4
JOINT_PWM_CHANNELS[5] = 5

JOINT_ADC_INPUT = []
JOINT_ADC_INPUT[0] = 0
JOINT_ADC_INPUT[1] = 1
JOINT_ADC_INPUT[2] = 2
JOINT_ADC_INPUT[3] = 3
JOINT_ADC_INPUT[4] = 4
JOINT_ADC_INPUT[5] = 5

JOINT_VALUE_MAP_PATH = []
JOINT_VALUE_MAP_PATH[0] = 'data/angle_ads_value_map_joint_0.csv'

#MISC SETTINGS
PWM_BOARD_RESOLUTION = 4096 # PWM control board resolution
SERVO_MOTOR_FREQUENCY = 50 #In Hz


SERVO_MOTOR_DUTY_CYCLE_MIN = 2.5  # Min duty cycle, in %
SERVO_MOTOR_DUTY_CYCLE_MAX = 12.5  # Max duty cycle, in %
